// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fed-world/AgentCard.tsx": () => import("../components/mockups/fed-world/AgentCard.tsx"),
  "./components/mockups/fed-world/WorldView.tsx": () => import("../components/mockups/fed-world/WorldView.tsx")
};
